version: "3.9"
services:
  chatapp-go:
    container_name: chatapp-go
    build:
      context: ../first
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    # depends_on:
    #   - nginx
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
      - RABBITMQ_URL=amqp://shahab:83000000@rabbitmq:5672/my_chat_app
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - my-chatapp-net # connect to the user-defined network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80 # expose and map the nginx port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # mount the custom nginx.conf file
    depends_on:
      - chatapp-go
    networks:
      - my-chatapp-net # connect to the user-defined network

networks:
  my-chatapp-net: # create a user-defined bridge network for the containers
